### ISSUE TITLE
Needs ignore some peers

### ISSUE THREAD

**Issue by ufm** [ygguser/peers_updater#1]
Hi!
I propose to add such a feature:

`-i, --ignore <VALUE>   A space-separated string with the URIs of the peers that should always be ignored`

For example, it is needed so that their own addresses are not added to the config.

**Comment by ygguser** [comment]
Ok. I will add this parameter.

**Comment by ygguser** [comment]
Added the option in https://github.com/ygguser/peers_updater/commit/511d0f5430a4d7c9e3e69773d4e7471b33e4af03. It will work when adding peers to the config and using the API, but it will not be used when printing the list (option `-p`).
So will it be ok?
Or would you like this option to work when prining as well?

**Comment by ufm** [comment]
I think this parameter should behave the same as `-e`

**Comment by ygguser** [comment]
Ok. This is implemented in the latest release.
