### ISSUE TITLE
macos build

### ISSUE THREAD

**Issue by rinchen** [ygguser/peers_updater#19]
Hi,

For macOS on an intel processor I needed to run `cargo build --target=x86_64-apple-darwin` otherwise zbuild would error.

**Comment by ygguser** [comment]
Hi,
Unfortunately, at the moment, I can't test the build on macOS, due to the lack of one...
I would recommend adding `--release` to the line you provided to get an optimized binary file.
And I could add `x86_64-apple-darwin` to the GitHub Actions CI script to build it automatically with the next release.

**Comment by ygguser** [comment]
Please test the build from the [release](https://github.com/ygguser/peers_updater/releases/tag/0.3.2).

**Comment by rinchen** [comment]
'./peers_updater' terminated by signal SIGKILL (Forced quit)

dtrace: failed to execute ./peers_updater: Bad executable (or shared library)

**Comment by rinchen** [comment]
Running on macos 14.1 I've had to update the build command to

`cargo build --release --target=x86_64h-apple-darwin`

because the non-"h" variant abends on clang.  I found the "h" variant by searching the internet and then asking the installed rust for available targets. I can't get the code to build properly (not a rust person) as it's missing two crates. rustup is not available on macos. I have rust installed via brew.sh. 

Here is what is available view brew:

~ brew search rust                                                                                                                      
==> Formulae
c2rust                   rust ✔                   rustc-completion         rustscan                 shadowsocks-rust         virustotal-cli
choose-rust              rust-analyzer            rustfmt                  rustup-init              uncrustify               rush

Here is the top of the build...

~ cargo build --release --target=x86_64h-apple-darwin                                                                                     0 [11:15:56]
   Compiling libc v0.2.149
   Compiling cfg-if v1.0.0
   Compiling spin v0.9.8
   Compiling untrusted v0.9.0
   Compiling crc32fast v1.3.2
   Compiling rustls v0.21.8
   Compiling serde v1.0.190
   Compiling adler v1.0.2
   Compiling strsim v0.10.0
   Compiling num-traits v0.2.17
   Compiling minreq v2.11.0
   Compiling clap_lex v0.6.0
   Compiling regex-syntax v0.8.2
   Compiling log v0.4.20
   Compiling anstyle v1.0.4
   Compiling webpki-roots v0.25.2
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64h-apple-darwin` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64h-apple-darwin`

error[E0463]: can't find crate for `compiler_builtins`

**Comment by ygguser** [comment]
I'm afraid I won't be able to build it for x86_64**h**-apple-darwin (there is no ready-made toolchain). I can only suggest that you try my x86_64-apple-darwin build again or try to build it yourself (I have changed the build settings a little).
[x86_64-apple-darwin.zip](https://github.com/ygguser/peers_updater/files/13208043/x86_64-apple-darwin.zip)

**Comment by rinchen** [comment]
W00t! Your file above worked!

**Comment by ygguser** [comment]
Great! :)
