### ISSUE TITLE
Cannot compile on Windows

### ISSUE THREAD

**Issue by SouceCalve** [ygguser/peers_updater#3]
I cant compile on windows/
Installed: cargo 1.66.0 (d65d197ad 2022-11-15) and rust(installed by cargo)/
Error log:
error: failed to run custom build command for `openssl-sys v0.9.79`

Caused by:
  process didn't exit successfully: `C:\Users\User\Desktop\peers_updater-master\target\release\build\openssl-sys-a452beaf6f62daf0\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rustc-cfg=openssl
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  running "perl" "./Configure" "--prefix=C:\\Users\\User\\Desktop\\peers_updater-master\\target\\release\\build\\openssl-sys-2329d5f1e985b049\\out\\openssl-build\\install" "--openssldir=SYS$MANAGER:[OPENSSL]" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-engine" "no-asm" "VC-WIN64A"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', C:\Users\User\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-src-111.24.0+1.1.1s\src\lib.rs:496:39

**Comment by ygguser** [comment]
1. Install OpenSSL from http://slproweb.com/products/Win32OpenSSL.html into `C:\Program Files\OpenSSL-Win64` (non-light version).
2. Download the file https://curl.se/ca/cacert.pem in the `C:\Program Files\OpenSSL-Win64\certs` directory (if there is no directory, create one).
3. Run the command prompt with administrator rights. Further actions are performed in it.
4. Set environment variables:
```
setx /m OPENSSL_CONF "C:\Program Files\OpenSSL-Win64\bin\openssl.cfg"
setx /m PATH %PATH%;"C:\Program Files\OpenSSL-Win64\bin"
```
5. Go to the peers_updater directory: `cd peers_updater`
6. Set the following environment variables:
```
set OPENSSL_NO_VENDOR=1
set RUSTFLAGS=-Ctarget-feature=+crt-static
set SSL_CERT_FILE="C:\Program Files\OpenSSL-Win64\certs\cacert.pem"
set OPENSSL_DIR=C:\Program Files\OpenSSL-Win64
```
7. Run the build: `cargo build --release`
