### ISSUE TITLE
deduplicate

### ISSUE THREAD

**Issue by perguth** [ygguser/peers_updater#5]
Using

> 0 0 * * 0 /path/peers_updater -u -n 24 -r -c /etc/yggdrasil.conf >/dev/null 2>&1

one ends up with quite a lot duplicates where the same peer is connected using `tcp` as well as `tls`.

**Comment by ygguser** [comment]
For now, I can advise using the `-i "tls:/"` flag, which can be used to weed out peers with a tls-connection (the same can be done with tcp).
Soon I will try to fix the problem with adding the same peer with different connection protocols.

By the way, I think you are adding too many nodes (24). The developers [recommend](https://github.com/yggdrasil-network/public-peers#how-do-i-pick-peers) using 2-3 geographically closest peers.
