### ISSUE TITLE
выбрать регион и страну

### ISSUE THREAD

**Issue by whoizit** [ygguser/peers_updater#6]
или несколько регионов и стран или иметь возможность исключить страну из списка пиров
очень не хватает

**Comment by ygguser** [comment]
Разработчики Yggdrasil [рекомендуют](https://github.com/yggdrasil-network/public-peers#how-do-i-pick-peers) указывать в конфигурационном файле 2-3 географически ближайших к вам пира. Географически ближайших - потому, что так задержка сети будет минимальной.
Если же вы будете игнорировать какие-то регионы/страны, есть вероятность, что вы ошибетесь и исключите регион, с которым задержка будет минимальной. И это может значительно повлиять на срорость работы и стабильность сети.
[peer_updater](https://github.com/ygguser/peers_updater) автоматически выбирает узлы с наименьшим временем отклика.
Так ли необходимо делать фильтр по странам/регионам?

**Comment by whoizit** [comment]
я не доверяю российским пирам, ближайшим ко мне

**Comment by ygguser** [comment]
Если вы не доверяете конкретным пирам, вы можете перечислить их после параметра `--ignore` - они не будут добавляться в конфигурацию.
В целом, анонимность в Yggdrasil может быть обеспечена только подключением через [tor](https://github.com/yggdrasil-network/public-peers/blob/master/other/tor.md) или [i2p](https://github.com/yggdrasil-network/public-peers/blob/master/other/i2p.md).
Выбор пиров не из своей страны - это малоэффективная мера в этом контексте. Как простые пользователи, так и различные компании и органиации из России используют VPS c размещением по всему миру и вы не можете быть уверенным в том, что подключаетесь к честному и уважающему приватность узлу.

**Comment by whoizit** [comment]
я ничего не говорил про анонимность. Мне просто нужно соединение сразу за пределами страны, потому что мой интерес лежит за пределами страны и таким образом я уменьшаю пинг, особенно если сразу подключусь к пирам той страны в которой находится нужный мне сервер

```
exclude_country='russia'
include_country='sweden|finland'
count=3

peers=$(peers_updater -p -i tcp:/ \ 
  | grep -Ev "URI|---|${exclude_country}" \
  | grep -E ${include_country} \
  | head -n${count} \
  | cut -d'|' -f1 \
  | tr -d '[:blank:]'
)

echo $peers
```

**Comment by ygguser** [comment]
Добавил опцию `-I` (`--ignore_country`) - попробуйте. 
[x86_64-unknown-linux-gnu.zip](https://github.com/ygguser/peers_updater/files/10725765/x86_64-unknown-linux-gnu.zip)

**Comment by whoizit** [comment]
работает
```
sudo peers_updater --ignore tcp:/ --ignore_country russia --update_cfg --restart 
```

**Comment by ygguser** [comment]
Закрываем?
